name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf automake libtool pkg-config build-essential cmake libffi-dev libssl-dev libltdl-dev zlib1g-dev

      - name: Install Python tools
        run: |
          pip install --upgrade pip setuptools wheel cython
          pip install buildozer

      - name: Clean previous build
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Create buildozer.spec
        run: |
          echo '[app]' > buildozer.spec
          echo 'title = Gestion commande EN' >> buildozer.spec
          echo 'package.name = gestion_commande_en' >> buildozer.spec
          echo 'package.domain = org.en' >> buildozer.spec
          echo 'source.dir = .' >> buildozer.spec
          echo 'source.include_exts = py,png,jpg,kv,ttf,db' >> buildozer.spec
          echo 'version = 0.1' >> buildozer.spec
          echo 'requirements = python3,kivy,reportlab,pyjnius' >> buildozer.spec
          echo 'orientation = portrait' >> buildozer.spec
          echo 'android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE' >> buildozer.spec
          echo 'android.api = 30' >> buildozer.spec
          echo 'android.minapi = 21' >> buildozer.spec
          echo 'android.ndk = 25c' >> buildozer.spec
          echo 'android.accept_sdk_license = True' >> buildozer.spec
          echo 'fullscreen = 0' >> buildozer.spec
          echo 'android.archs = armeabi-v7a' >> buildozer.spec
          echo 'log_level = 2' >> buildozer.spec

      - name: Display buildozer.spec content
        run: cat buildozer.spec

      - name: Build APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mon-apk
          path: bin/*.apk