name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            autoconf automake libtool pkg-config \
            build-essential cmake \
            libffi-dev libssl-dev \
            libltdl-dev \
            zlib1g-dev

      - name: Install Python tools
        run: |
          pip install --upgrade pip setuptools wheel cython
          pip install buildozer

      - name: Configure buildozer
        run: |
          # Forcer l'utilisation d'une version spécifique du NDK
          buildozer init
          sed -i 's/android.ndk = .*/android.ndk = 23b/' buildozer.spec
          sed -i 's/android.api = .*/android.api = 33/' buildozer.spec
          sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec

      - name: Build APK
        run: |
          # Nettoyer le cache avant la construction
          rm -rf .buildozer
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mon-apk
          path: bin/*.apk