name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf automake libtool pkg-config build-essential cmake libffi-dev libssl-dev libltdl-dev zlib1g-dev

      - name: Install Python tools
        run: |
          pip install --upgrade pip setuptools wheel cython
          pip install buildozer

      - name: Clean previous build
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Create fresh buildozer.spec
        run: |
          cat > buildozer.spec << 'EOF'
          [app]
          
          title = Gestion commande EN
          package.name = gestion_commande_en
          package.domain = org.en
          
          source.dir = .
          source.include_exts = py,png,jpg,kv,ttf,db
          
          version = 0.1
          
          requirements = python3,kivy
          
          orientation = portrait
          
          android.permissions = INTERNET
          
          android.api = 30
          android.minapi = 21
          android.ndk = 23b
          android.sdk = 30
          
          android.accept_sdk_license = True
          
          fullscreen = 0
          
          android.archs = armeabi-v7a
          
          android.gradle = False
          EOF

      - name: Build APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mon-apk
          path: bin/*.apk